---
- name: Finalize installation of Ansible required infrastructure.
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  tasks:
    - name: Install dependencies.
      include_role:
        name: ansible_infrastructure